export type { Song, SongWithMeta } from "./song";
export type { Playlist, PlaylistWithSongs } from "./playlist";
export type { Profile, PlayHistory } from "./user";
export type { PlayMode, PlayerState, PlayerActions, PlayerStore } from "./player";
export type {
  LoadingState,
  LyricLine,
  AudioState,
  QueueState,
  PlayerSnapshot,
  AudioEventCallbacks,
  Artist,
  Album,
  SearchResult,
} from "./music";
export type {
  UserState,
  UserInfo,
  LikedSongRecord,
  LikedSongWithMeta,
  RecentlyPlayedRecord,
  RecentlyPlayedWithMeta,
  UserPlaylist,
  PlaylistWithSongsDetail,
  FavoritePlaylistRecord,
  FavoritePlaylistWithMeta,
  PlaylistSongRecord,
  LibraryData,
} from "./library";
export type {
  CommentRecord,
  CommentWithProfile,
  CommentUserProfile,
  CommentLikeRecord,
  CommentReplyRecord,
  CommentReplyWithProfile,
  PageParam,
  CommentPage,
  ReplyPage,
  CommentSortType,
  SocialState,
} from "./social";
export type {
  NetworkState,
  CacheStats,
  InstallState,
  SystemState,
  SystemActions,
  SystemStore,
} from "./system";
export type {
  ProviderHealthSnapshot,
  ProviderHealthMap,
  ProviderStatus,
  FallbackReason,
  ProviderState,
  ProviderActions,
  ProviderStore,
  RetryConfig,
  ProviderEntry,
  ProxyConfig,
} from "./provider";
export { DEFAULT_RETRY_CONFIG } from "./provider";
export type {
  RecoveryState,
  RecoveryResult,
  RecoveryActions,
  RecoveryStore,
} from "./recovery";
export type {
  DownloadStatus,
  DownloadTask,
  DownloadQueue,
  DownloadProgress,
} from "./download";
export type {
  WatchdogEventType,
  WatchdogRecoveryAction,
  WatchdogEvent,
  WatchdogRecovery,
  WatchdogState,
  WatchdogConfig,
  ProviderScore,
  ProviderScoreMap,
  SelfHealingConfig,
  CacheGovernanceConfig,
  CacheCleanupResult,
  TelemetryMetric,
  ProviderMetrics,
  PlaybackMetrics,
  CacheMetrics,
  StartupMetrics,
  TelemetrySnapshot,
  TelemetryStore,
  ReleaseMode,
  ReleaseConfig,
} from "./phase9";
export { DEFAULT_WATCHDOG_CONFIG, DEFAULT_SELF_HEALING_CONFIG, DEFAULT_CACHE_GOVERNANCE_CONFIG, RELEASE_CONFIGS } from "./phase9";
export type {
  RuntimeConfig,
  RuntimeProviderEntry,
  RuntimeCacheStrategy,
  RuntimeDebugConfig,
  RuntimeExperimentFlags,
  ConfigOverride,
  BackupScope,
  BackupManifest,
  BackupBundle,
  BackupData,
  PlaylistBackup,
  CacheIndexEntry,
  BackupMetadata,
  BackupResult,
  RestoreResult,
  MigrationTarget,
  MigrationStep,
  MigrationRecord,
  MigrationState,
  MigrationResult,
  ProviderHotConfig,
  ProviderSwitchEvent,
  ProviderReloadState,
  DeploymentMode,
  DeploymentProfile,
  RecoveryLevel,
  RecoveryCheckpoint,
  RecoverySnapshot,
  RecoveryResult2,
  MemorySnapshot,
  MemoryPressureEvent,
  IntegrityCheck,
  IntegrityReport,
} from "./phase10";
export { DEFAULT_RUNTIME_CONFIG, DEPLOYMENT_PROFILES } from "./phase10";

// Phase 11 — AI原生工程体系
export type {
  DiagnosticsSeverity,
  DiagnosticsScope,
  DiagnosticsReport,
  ProviderDiagnosticsItem,
  CacheDiagnosticsItem,
  PlaybackDiagnosticsItem,
  StoreDiagnosticsItem,
  ArchitectureSnapshot,
  SnapshotDiff,
  DirectoryStats,
  StoreSnapshot,
  ProviderSnapshot,
  GovernanceSeverity,
  GovernanceReport,
  GovernanceCheckItem,
  MaintenanceModeType,
  MaintenanceModeState,
  MaintenanceRestrictions,
} from "./phase11";

// Phase 12 — 最终私用生态闭环
export type {
  LocalMediaType,
  LocalMediaFile,
  LocalAudioMetadata,
  LocalMediaIndex,
  LocalPlaylistData,
  LocalMediaProviderConfig,
  RemoteStorageType,
  RemoteStorageConfig,
  RemoteStorageStatus,
  RemoteFileEntry,
  ScanStatus,
  ScanConfig,
  ScanProgress,
  ScanResult,
  DuplicateGroup,
  ScanError,
  MediaHashCache,
  AutonomyTaskType,
  AutonomyTaskStatus,
  AutonomyTask,
  AutonomyTaskResult,
  SystemHealthReport,
  ProviderHealthEntry,
  CacheHealthEntry,
  StoreHealthEntry,
  RecoveryHealthEntry,
  SystemIssue,
  AIAutonomyConfig,
  PipelineStage,
  PipelineStatus,
  PipelineStageResult,
  PipelineError,
  GovernancePipelineResult,
  DegradedLevel,
  DegradedModeConfig,
  DegradedState,
  RuntimeProfileType,
  RuntimeProfile,
  ProfileRestrictions,
  ProfileFeatures,
  ArchiveScope,
  ArchiveManifest,
  ArchiveEntry,
  ArchiveConfig,
  ArchiveResult,
  ArchiveRestoreResult,
  ArchiveRestoreError,
  SystemStatusSnapshot,
  ProviderStatusEntry,
  CacheStatusEntry,
  RecoveryStatusEntry,
  AIAutonomyStatusEntry,
} from "./phase12";
export {
  DEFAULT_LOCAL_MEDIA_CONFIG,
  DEFAULT_AI_AUTONOMY_CONFIG,
  DEFAULT_DEGRADED_CONFIG,
  DEFAULT_ARCHIVE_CONFIG,
  DEFAULT_SCAN_CONFIG,
  RUNTIME_PROFILES,
} from "./phase12";

// Phase 13 — 最终长期冻结版
export type {
  FrozenSection,
  FrozenMode,
  FrozenSectionConfig,
  FrozenRuntimeState,
  FrozenViolation,
  FrozenRuntimeConfig,
  MaintenanceTaskType,
  MaintenanceTaskPriority,
  MaintenanceTask,
  MaintenanceLoopState,
  MaintenanceReport,
  MaintenanceTaskResult,
  IsolationDomain,
  IsolationLevel,
  IsolationConfig,
  IsolationState,
  IsolationReport,
  HealingAction,
  HealingResult,
  HealingHistory,
  StabilityScore,
  SnapshotType,
  SnapshotEntry,
  RotationConfig,
  RotationResult,
  DisasterType,
  DisasterScenario,
  RecoveryStrategy,
  RecoveryStep,
  RecoveryPlan,
  RecoveryResult as DisasterRecoveryResult,
  RecoveryError,
  LongTermStabilityMetrics,
  ProjectFreezeState,
} from "./phase13";
export {
  DEFAULT_FROZEN_RUNTIME_CONFIG,
  DEFAULT_MAINTENANCE_TASKS,
  DEFAULT_ISOLATION_CONFIGS,
  DEFAULT_ROTATION_CONFIG,
  DISASTER_SCENARIOS,
} from "./phase13";

// Phase 15 — Smart Music UX
export type {
  PlayEvent,
  SongPlayCount,
  ArtistPlayCount,
  DailyPlayRecord,
  AnalyticsData,
  SmartPlaylistMode,
  SmartPlaylistConfig,
  SleepTimerDuration,
  SleepTimerState,
  FocusModeState,
} from "./phase15";

// Phase 17 — Production Hardening
export type {
  CrashRecoveryState,
  CrashRecoveryResult,
  ProviderMetricsV2,
  HourlyBucket,
  ProviderTelemetrySnapshot,
  LRUEntry,
  CacheGovernanceConfigV2,
  BatteryState,
  BatteryOptimizationConfig,
  StabilityEvent,
  StabilityReport,
  ErrorBoundaryConfig,
  ErrorLogEntry,
} from "./phase17";
export {
  DEFAULT_CACHE_GOVERNANCE_CONFIG_V2,
  DEFAULT_BATTERY_OPTIMIZATION,
} from "./phase17";

// Phase 18A — Advanced Audio Experience Foundation
export type {
  CrossfadeCurve,
  CrossfadeConfig,
  EQPresetName,
  EQBandDefinition,
  EQPreset,
  EQPresets,
  EQState,
  NormalizationConfig,
  VisualizationMode,
  VisualizationConfig,
  AudioSessionEventType,
  AudioSessionEvent,
} from "./phase18";
export {
  DEFAULT_CROSSFADE_CONFIG,
  EQ_BANDS,
  DEFAULT_EQ_STATE,
  DEFAULT_NORMALIZATION_CONFIG,
  DEFAULT_VISUALIZATION_CONFIG,
} from "./phase18";
