/**
 * Phase 11 — Maintenance Mode Manager
 *
 * 管理应用的运行模式切换。支持:
 * - release: 正常生产模式
 * - maintenance: 维护模式 (显示维护横幅)
 * - degraded: 降级模式 (Provider大量失效时)
 * - provider_emergency: Provider紧急模式 (全部降级到Mock)
 */

import type { MaintenanceModeType, MaintenanceModeState, MaintenanceRestrictions } from "@/types/phase11";

const MODE_STORAGE_KEY = "music_maintenance_mode";

const RESTRICTIONS: Record<MaintenanceModeType, MaintenanceRestrictions> = {
  release: {
    disableNewFeatures: false,
    disableProviderSwitching: false,
    forceMockProvider: false,
    disableWriteOperations: false,
    enableVerboseLogging: false,
    disableCacheCleanup: false,
    showMaintenanceBanner: false,
  },
  maintenance: {
    disableNewFeatures: true,
    disableProviderSwitching: false,
    forceMockProvider: false,
    disableWriteOperations: true,
    enableVerboseLogging: true,
    disableCacheCleanup: false,
    showMaintenanceBanner: true,
  },
  degraded: {
    disableNewFeatures: true,
    disableProviderSwitching: false,
    forceMockProvider: false,
    disableWriteOperations: false,
    enableVerboseLogging: true,
    disableCacheCleanup: false,
    showMaintenanceBanner: true,
  },
  provider_emergency: {
    disableNewFeatures: true,
    disableProviderSwitching: true,
    forceMockProvider: true,
    disableWriteOperations: false,
    enableVerboseLogging: true,
    disableCacheCleanup: false,
    showMaintenanceBanner: true,
  },
};

export class MaintenanceMode {
  private static instance: MaintenanceMode;
  private state: MaintenanceModeState;

  private constructor() {
    this.state = this.loadState();
  }

  static getInstance(): MaintenanceMode {
    if (!MaintenanceMode.instance) {
      MaintenanceMode.instance = new MaintenanceMode();
    }
    return MaintenanceMode.instance;
  }

  getState(): MaintenanceModeState {
    return { ...this.state };
  }

  getCurrentMode(): MaintenanceModeType {
    return this.state.currentMode;
  }

  getRestrictions(): MaintenanceRestrictions {
    return { ...RESTRICTIONS[this.state.currentMode] };
  }

  isFeatureDisabled(feature: keyof MaintenanceRestrictions): boolean {
    return RESTRICTIONS[this.state.currentMode][feature];
  }

  enterMode(mode: MaintenanceModeType, reason: string): void {
    if (mode === this.state.currentMode) return;

    const previous = this.state.currentMode;
    this.state = {
      currentMode: mode,
      previousMode: previous,
      enteredAt: Date.now(),
      reason,
      restrictions: { ...RESTRICTIONS[mode] },
    };

    this.persist();
  }

  exitMaintenanceMode(): void {
    this.enterMode("release", "维护结束，恢复正常模式");
  }

  /**
   * 自动检测是否需要进入降级模式
   * 基于 Provider 健康状态自动切换
   */
  async autoEvaluateProviderEmergency(): Promise<boolean> {
    try {
      const { getProviderManager } = await import(
        "@/music-source/providers/provider-manager/ProviderManager"
      );
      const manager = getProviderManager();
      const healthMap = manager.getAllHealth();
      const priorityList = manager.getPriorityList();

      const realProviders = Array.from(healthMap.entries()).filter(
        ([type]) => type !== "mock",
      );

      const healthyCount = realProviders.filter(([type, health]) => {
        return priorityList.includes(type) && health.successRate >= 70;
      }).length;

      const totalEnabled = realProviders.filter(([type]) => {
        return priorityList.includes(type);
      }).length;

      if (totalEnabled === 0 && this.state.currentMode !== "provider_emergency") {
        this.enterMode("provider_emergency", "所有真实Provider不可用，自动进入紧急模式");
        return true;
      }

      if (
        healthyCount === 0 &&
        totalEnabled > 0 &&
        this.state.currentMode !== "degraded"
      ) {
        this.enterMode("degraded", "所有Provider健康评分低于阈值");
        return true;
      }

      if (
        healthyCount > 0 &&
        (this.state.currentMode === "provider_emergency" || this.state.currentMode === "degraded")
      ) {
        this.enterMode("release", "Provider恢复可用，自动退出降级");
        return true;
      }

      return false;
    } catch {
      return false;
    }
  }

  /**
   * 生成维护状态 Markdown 报告
   */
  generateStatusReport(): string {
    const s = this.state;
    const date = new Date(s.enteredAt).toISOString();
    return [
      `# Maintenance Mode Status — ${date}`,
      "",
      `- **Current Mode:** ${s.currentMode}`,
      `- **Previous Mode:** ${s.previousMode ?? "none"}`,
      `- **Entered At:** ${date}`,
      `- **Reason:** ${s.reason}`,
      "",
      "## Active Restrictions",
      "",
      ...Object.entries(s.restrictions)
        .filter(([, v]) => v)
        .map(([k]) => `- ${k}`),
      "",
      "---",
      "> Auto-generated by MaintenanceMode | Phase 11",
    ].join("\n");
  }

  // ─── Private ───

  private loadState(): MaintenanceModeState {
    try {
      const raw = localStorage.getItem(MODE_STORAGE_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as MaintenanceModeState;
        // 恢复时强制使用 release 模式，维护模式不持久化
        if (saved.currentMode !== "release") {
          return this.defaultState();
        }
        return saved;
      }
    } catch {
      // fall through
    }
    return this.defaultState();
  }

  private defaultState(): MaintenanceModeState {
    return {
      currentMode: "release",
      previousMode: null,
      enteredAt: Date.now(),
      reason: "系统正常启动",
      restrictions: RESTRICTIONS.release,
    };
  }

  private persist(): void {
    try {
      localStorage.setItem(MODE_STORAGE_KEY, JSON.stringify(this.state));
    } catch {
      // localStorage full — silently skip
    }
  }
}

export function getMaintenanceMode(): MaintenanceMode {
  return MaintenanceMode.getInstance();
}
